# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
accordion-padding = 50

after-startup-command = [
  'exec-and-forget borders active_color=0xffd3e2ff inactive_color=0xff494d64 width=4.5'
]

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript
alt-enter = '''exec-and-forget osascript -e '
tell application "Terminal"
    do script
    activate
end tell'
'''

alt-keypad4 = 'focus left'
alt-keypad2 = 'focus down'
alt-keypad8 = 'focus up'
alt-keypad6 = 'focus right'

alt-shift-keypad4 = 'move left'
alt-shift-keypad2 = 'move down'
alt-shift-keypad8 = 'move up'
alt-shift-keypad6 = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-h = 'split horizontal'
alt-v = 'split vertical'

alt-f = 'fullscreen'

alt-w = 'layout accordion horizontal vertical'
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-ctrl-keypad4 = 'join-with left'
alt-ctrl-keypad6 = 'join-with right'
alt-ctrl-keypad8 = 'join-with up'
alt-ctrl-keypad2 = 'join-with down'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[gaps]
inner.horizontal = 15
inner.vertical =   15
outer.left =       15
outer.bottom =     15
outer.top =        15
outer.right =      15

[workspace-to-monitor-force-assignment]
1 = 'secondary'                            # Monitor sequence number from left to right. 1-based indexing
2 = 'secondary'                            # Monitor sequence number from left to right. 1-based indexing
3 = 'secondary'                            # Monitor sequence number from left to right. 1-based indexing
4 = 'main'                            # Monitor sequence number from left to right. 1-based indexing
5 = 'main'                            # Monitor sequence number from left to right. 1-based indexing




